### PR TITLE
Add required deployment variables for MCE deploy.

### PR DESCRIPTION
**Pull request by jnpacker**
* Update values.yaml
* Update the deployment template for the hypershift-deployment-controller

Signed-off-by: Joshua Packer <jpacker@redhat.com>

### CODE REVIEW

**Comment by jnpacker** [comment]
Issue Reference: https://github.com/stolostron/backlog/issues/18754
Additional reference: https://github.com/stolostron/backlog/issues/20258

**Review by ianzhang366 — APPROVED** [review]

**Pull request merged**
